<!--

function Social_Load() { 
var d=document; if(d.images){ if(!d.Social) d.Social=new Array();
var i,j=d.Social.length,a=Social_Load.arguments; for(i=0; i<a.length; i++)
if (a[i].indexOf("#")!=0){ d.Social[j]=new Image; d.Social[j++].src=a[i];}}
}

Social_Load('http://asp.net.tr/img/wong_trans_ani.gif','http://asp.net.tr/img/webnews_trans_ani.gif','http://asp.net.tr/img/facebook_trans_ani.gif','http://asp.net.tr/img/icio_trans_ani.gif','http://asp.net.tr/img/oneview_trans_ani.gif','http://asp.net.tr/img/newskick_trans_ani.gif','http://asp.net.tr/img/favit_trans_ani.gif','http://asp.net.tr/img/kledy_trans_ani.gif','http://asp.net.tr/img/seekxl_trans_ani.gif','http://asp.net.tr/img/newsider_trans_ani.gif','http://asp.net.tr/img/linksilo_trans_ani.gif','http://asp.net.tr/img/sbdk_trans_ani.gif','http://asp.net.tr/img/boni_trans_ani.gif','http://asp.net.tr/img/power_trans_ani.gif','http://asp.net.tr/img/readster_trans_ani.gif','http://asp.net.tr/img/folkd_trans_ani.gif','http://asp.net.tr/img/yigg_trans_ani.gif','http://asp.net.tr/img/linkarena_trans_ani.gif','http://asp.net.tr/img/digg_trans_ani.gif','http://asp.net.tr/img/juptags_trans_ani.gif','http://asp.net.tr/img/del_trans_ani.gif','http://asp.net.tr/img/upchuckr_trans_ani.gif','http://asp.net.tr/img/reddit_trans_ani.gif','http://asp.net.tr/img/simpy_trans_ani.gif','http://asp.net.tr/img/stumbleupon_trans_ani.gif','http://asp.net.tr/img/slashdot_trans_ani.gif','http://asp.net.tr/img/netscape_trans_ani.gif','http://asp.net.tr/img/furl_trans_ani.gif','http://asp.net.tr/img/yahoo_trans_ani.gif','http://asp.net.tr/img/spurl_trans_ani.gif','http://asp.net.tr/img/google_trans_ani.gif','http://asp.net.tr/img/blinklist_trans_ani.gif','http://asp.net.tr/img/blogmarks_trans_ani.gif','http://asp.net.tr/img/diigo_trans_ani.gif','http://asp.net.tr/img/technorati_trans_ani.gif','http://asp.net.tr/img/newsvine_trans_ani.gif','http://asp.net.tr/img/blinkbits_trans_ani.gif','http://asp.net.tr/img/ma.gnolia_trans_ani.gif','http://asp.net.tr/img/smarking_trans_ani.gif','http://asp.net.tr/img/Twitter.png')
function schnipp() { 
var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function schnupp(n, d) { 
  var p,i,x; if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
  d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=schnupp(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
  }

function schnapp() { 
  var i,j=0,x,a=schnapp.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
  if ((x=schnupp(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
  }

//-->
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.facebook.com/\" onClick=\"window.open(\'http://www.facebook.com/sharer.php?u=\'+encodeURIComponent(location.href)+\'&amp;t=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Facebook.com\" onMouseOver=\"schnapp(\'Facebook\',\'\',\'http://asp.net.tr/img/facebook_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/facebook_trans.gif\" alt=\"Add to: Facebook.com\" name=\"Facebook\" border=\"0\" id=\"Facebook\"> </a>");
document.writeln("<a style=\"text-decoration:none;\" href=\"http://www.twitter.com/\" target=\"_Blank\" title=\"Add to: Twitter.com\" onMouseOver=\"schnapp(\'Information\',\'\',\'http://asp.net.tr/img/Twitter.png\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/Twitter.png\" alt=\"Sosyal Imleme\" name=\"Information\" border=\"0\" id=\"Information\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.mister-wong.de/\" onClick=\"window.open(\'http://www.mister-wong.de/index.php?action=addurl&amp;bm_url=\'+encodeURIComponent(location.href)+\'&amp;bm_notice=&amp;bm_description=\'+encodeURIComponent(document.title)+\'&amp;bm_tags=\');return false;\" title=\"Add to: Mr. Wong\" onMouseOver=\"schnapp(\'wong\',\'\',\'http://asp.net.tr/img/wong_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/wong_trans.gif\" alt=\"Add to: Mr. Wong\" name=\"wong\" border=\"0\" id=\"wong\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.webnews.de/\" onClick=\"window.open(\'http://www.webnews.de/einstellen?url=\'+encodeURIComponent(document.location)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Webnews\" onMouseOver=\"schnapp(\'Webnews\',\'\',\'http://asp.net.tr/img/webnews_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/webnews_trans.gif\" alt=\"Add to: Webnews\" name=\"Webnews\" border=\"0\" id=\"Webnews\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.icio.de/\" onClick=\"window.open(\'http://www.icio.de/add.php?url=\'+encodeURIComponent(location.href));return false;\" title=\"Add to: Icio\" onMouseOver=\"schnapp(\'Icio\',\'\',\'http://asp.net.tr/img/icio_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/icio_trans.gif\" alt=\"Add to: Icio\" name=\"Icio\" border=\"0\" id=\"Icio\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.oneview.de/\" onClick=\"window.open(\'http://www.oneview.de/quickadd/neu/addBookmark.jsf?URL=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Oneview\" onMouseOver=\"schnapp(\'Oneview\',\'\',\'http://asp.net.tr/img/oneview_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/oneview_trans.gif\" alt=\"Add to: Oneview\" name=\"Oneview\" border=\"0\" id=\"Oneview\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.linkarena.com/\" onClick=\"window.open(\'http://linkarena.com/bookmarks/addlink/?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title)+\'&amp;desc=&amp;tags=\');return false;\" title=\"Add to: Linkarena\" onMouseOver=\"schnapp(\'Linkarena\',\'\',\'http://asp.net.tr/img/linkarena_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/linkarena_trans.gif\" alt=\"Add to: Linkarena\" name=\"Linkarena\" border=\"0\" id=\"Linkarena\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.favoriten.de/\" onclick=\"window.open(\'http://www.favoriten.de/url-hinzufuegen.html?bm_url=\'+encodeURIComponent(location.href)+\'&amp;bm_title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Favoriten.de\" onmouseover=\"schnapp(\'Favoriten\',\'\',\'http://asp.net.tr/img/favoriten_trans_ani.gif\',1)\" onmouseout=\"schnipp()\"><img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/favoriten_trans.gif\" alt=\"Add to: Favoriten.de\" name=\"Favoriten\" border=\"0\" id=\"Favoriten\"/></a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://social-bookmarking.seekxl.de/\" onClick=\"window.open(\'http://social-bookmarking.seekxl.de/?add_url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Seekxl\" onMouseOver=\"schnapp(\'Seekxl\',\'\',\'http://asp.net.tr/img/seekxl_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/seekxl_trans.gif\" alt=\"Add to: Seekxl\" name=\"Seekxl\" border=\"0\" id=\"Seekxl\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.kledy.de/\" onclick=\"window.open(\'http://www.kledy.de/submit.php?url=\'+(document.location.href));return false;\" title=\"Add to: Kledy.de\" onmouseover=\"schnapp(\'Kledy\',\'\',\'http://asp.net.tr/img/kledy_trans_ani.gif\',1)\" onmouseout=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/kledy_trans.gif\" alt=\"Add to: Kledy.de\" name=\"Kledy\" border=\"0\" id=\"Kledy\"></a> ");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.social-bookmarking.dk/\" onclick=\"window.open(\'http://www.social-bookmarking.dk/bookmarks/?action=add&title=\'+encodeURIComponent(document.title)+\'&address=\'+(document.location.href));return false;\" title=\"Add to: Social Bookmark Portal\" onmouseover=\"schnapp(\'SocialBookmarkPortal\',\'\',\'http://asp.net.tr/img/sbdk_trans_ani.gif\',1)\" onmouseout=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/sbdk_trans.gif\" alt=\"Add to: Social Bookmark Portal\" name=\"SocialBookmarkPortal\" border=\"0\" id=\"SocialBookmarkPortal\"></a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.bonitrust.de/\" onClick=\"window.open(\'http://www.bonitrust.de/account/bookmark/?bookmark_url=\'+ unescape(location.href));return false;\" title=\"Add to: BoniTrust\" onMouseOver=\"schnapp(\'BoniTrust\',\'\',\'http://asp.net.tr/img/boni_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/boni_trans.gif\" alt=\"Add to: BoniTrust\" name=\"BoniTrust\" border=\"0\" id=\"BoniTrust\"></a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.power-oldie.com/\" onclick=\"window.open(\'http://www.power-oldie.com/\');return false;\" title=\"Add to: 40 Plus - Blog & Bookmark\" onmouseover=\"schnapp(\'Power\',\'\',\'http://asp.net.tr/img/power_trans_ani.gif\',1)\" onmouseout=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/power_trans.gif\" alt=\"Add to: 40 Plus - Blog & Bookmark\" name=\"Power\" border=\"0\" id=\"Power\"></a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.bookmarks.cc/\" onclick=\"window.open(\'http://www.bookmarks.cc/bookmarken.php?action=neu&amp;url=\'+(document.location.href)+\'&amp;title=\'+(document.title));return false;\" title=\"Add to: Bookmarks.cc\" onmouseover=\"schnapp(\'Bookmarkscc\',\'\',\'http://asp.net.tr/img/bookmarkscc_trans_ani.gif\',1)\" onmouseout=\"schnipp()\"><img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/bookmarkscc_trans.gif\" alt=\"Add to: Bookmarks.cc\" name=\"Bookmarkscc\" border=\"0\" id=\"Bookmarkscc\"></a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.shop-bookmarks.de/\" onclick=\"window.open(\'http://www.shop-bookmarks.de/bookmarken.php?action=neu&amp;url=\'+(document.location.href)+\'&amp;title=\'+(document.title));return false;\" title=\"Add to: Shop-Bookmarks.de\" onmouseover=\"schnapp(\'Shopbookmarks\',\'\',\'http://asp.net.tr/img/shopbookmarks_trans_ani.gif\',1)\" onmouseout=\"schnipp()\"><img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/shopbookmarks_trans.gif\" alt=\"Add to: Shop-Bookmarks.de\" name=\"Shopbookmarks\" border=\"0\" id=\"Shopbookmarkscc\"></a>");
document.writeln("<a style=\"text-decoration:none;\" href=\"http://www.favit.de/\" onclick=\"window.open(\'http://www.favit.de/submit.php?url=\'+(document.location.href));return false;\" title=\"Add to: Favit\" onmouseover=\"schnapp(\'Favit\',\'\',\'http://asp.net.tr/img/favit_trans_ani.gif\',1)\" onmouseout=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/favit_trans.gif\" alt=\"Add to: Favit\" name=\"Favit\" border=\"0\" id=\"Favit\"></a> ");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.newskick.de/\" onClick=\"window.open(\'http://www.newskick.de/submit.php?url=\'+(document.location.href));return false;\" title=\"Add to: Newskick\" onMouseOver=\"schnapp(\'Newskick\',\'\',\'http://asp.net.tr/img/newskick_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/newskick_trans.gif\" alt=\"Add to: Newskick\" name=\"Newskick\" border=\"0\" id=\"Newskick\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.newsider.de/\" onClick=\"window.open(\'http://www.newsider.de/submit.php?url=\'+(document.location.href));return false;\" title=\"Add to: Newsider\" onMouseOver=\"schnapp(\'Newsider\',\'\',\'http://asp.net.tr/img/newsider_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/newsider_trans.gif\" alt=\"Add to: Newsider\" name=\"Newsider\" border=\"0\" id=\"Newsider\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.linksilo.de\" onclick=\"window.open(\'http://www.linksilo.de/index.php?area=bookmarks&amp;func=bookmark_new&amp;addurl=\'+encodeURIComponent(location.href)+\'&amp;addtitle=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Linksilo\" onmouseover=\"schnapp(\'Linksilo\',\'\',\'http://asp.net.tr/img/linksilo_trans_ani.gif\',1)\" onmouseout=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/linksilo_trans.gif\" alt=\"Add to: Linksilo\" name=\"Linksilo\" border=\"0\" id=\"Linksilo\"/></a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.readster.de/\" onclick=\"window.open(\'http://www.readster.de/submit/?url=\'+encodeURIComponent(document.location)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Readster\" onmouseover=\"schnapp(\'Readster\',\'\',\'http://asp.net.tr/img/readster_trans_ani.gif\',1)\" onmouseout=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/readster_trans.gif\" alt=\"Add to: Readster\" name=\"Readster\" border=\"0\" id=\"Readster\"/></a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.folkd.com/\" onClick=\"window.open(\'http://www.folkd.com/submit/\'+(document.location.href));return false;\" title=\"Add to: Folkd\" onMouseOver=\"schnapp(\'Folkd\',\'\',\'http://asp.net.tr/img/folkd_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/folkd_trans.gif\" alt=\"Add to: Folkd\" name=\"Folkd\" border=\"0\" id=\"Folkd\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://yigg.de/\" onClick=\"window.open(\'http://yigg.de/neu?exturl=\'+encodeURIComponent(location.href));return false\" title=\"Add to: Yigg\"> <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/yigg_trans.gif\" alt=\"Add to: Yigg\" name=\"Yigg\" border=\"0\" id=\"Yigg\" onMouseOver=\"schnapp(\'Yigg\',\'\',\'http://asp.net.tr/img/yigg_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://digg.com/\" onClick=\"window.open(\'http://digg.com/submit?phase=2&amp;url=\'+encodeURIComponent(location.href)+\'&amp;bodytext=&amp;tags=&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Digg\" onMouseOver=\"schnapp(\'Digg\',\'\',\'http://asp.net.tr/img/digg_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/digg_trans.gif\" alt=\"Add to: Digg\" name=\"Digg\" border=\"0\" id=\"Digg\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://del.icio.us/\" onClick=\"window.open(\'http://del.icio.us/post?v=2&amp;url=\'+encodeURIComponent(location.href)+\'&amp;notes=&amp;tags=&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Del.icio.us\" onMouseOver=\"schnapp(\'Delicious\',\'\',\'http://asp.net.tr/img/del_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/del_trans.gif\" alt=\"Add to: Del.icio.us\" name=\"Delicious\" border=\"0\" id=\"Delicious\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://reddit.com/\" onClick=\"window.open(\'http://reddit.com/submit?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Reddit\" onMouseOver=\"schnapp(\'Reddit\',\'\',\'http://asp.net.tr/img/reddit_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/reddit_trans.gif\" alt=\"Add to: Reddit\" name=\"Reddit\" border=\"0\" id=\"Reddit\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.jumptags.com/\" onClick=\"window.open(\'http://www.jumptags.com/add/?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Jumptags\" onMouseOver=\"schnapp(\'Jumptags\',\'\',\'http://asp.net.tr/img/jumptags_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/jumptags_trans.gif\" alt=\"Add to: Jumptags\" name=\"Jumptags\" border=\"0\" id=\"Jumptags\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.simpy.com/\" onClick=\"window.open(\'http://www.simpy.com/simpy/LinkAdd.do?title=\'+encodeURIComponent(document.title)+\'&amp;tags=&amp;note=&amp;href=\'+encodeURIComponent(location.href));return false;\" title=\"Add to: Simpy\" onMouseOver=\"schnapp(\'Simpy\',\'\',\'http://asp.net.tr/img/simpy_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/simpy_trans.gif\" alt=\"Add to: Simpy\" name=\"Simpy\" border=\"0\" id=\"Simpy\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.stumbleupon.com/\" onClick=\"window.open(\'http://www.stumbleupon.com/submit?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: StumbleUpon\" onMouseOver=\"schnapp(\'StumbleUpon\',\'\',\'http://asp.net.tr/img/stumbleupon_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/stumbleupon_trans.gif\" alt=\"Add to: StumbleUpon\" name=\"StumbleUpon\" border=\"0\" id=\"StumbleUpon\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://slashdot.org/\" onClick=\"window.open(\'http://slashdot.org/bookmark.pl?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Slashdot\" onMouseOver=\"schnapp(\'Slashdot\',\'\',\'http://asp.net.tr/img/slashdot_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/slashdot_trans.gif\" alt=\"Add to: Slashdot\" name=\"Slashdot\" border=\"0\" id=\"Slashdot\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.netscape.com/\" onClick=\"window.open(\'http://www.netscape.com/submit/?U=\'+encodeURIComponent(location.href)+\'&amp;T=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Netscape\" onMouseOver=\"schnapp(\'Netscape\',\'\',\'http://asp.net.tr/img/netscape_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/netscape_trans.gif\" alt=\"Add to: Netscape\" name=\"Netscape\" border=\"0\" id=\"Netscape\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.furl.net/\" onClick=\"window.open(\'http://www.furl.net/storeIt.jsp?u=\'+encodeURIComponent(location.href)+\'&amp;keywords=&amp;t=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Furl\" onMouseOver=\"schnapp(\'Furl\',\'\',\'http://asp.net.tr/img/furl_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/furl_trans.gif\" alt=\"Add to: Furl\" name=\"Furl\" border=\"0\" id=\"Furl\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.yahoo.com/\" onClick=\"window.open(\'http://myweb2.search.yahoo.com/myresults/bookmarklet?t=\'+encodeURIComponent(document.title)+\'&amp;d=&amp;tag=&amp;u=\'+encodeURIComponent(location.href));return false;\" title=\"Add to: Yahoo\" onMouseOver=\"schnapp(\'Yahoo\',\'\',\'http://asp.net.tr/img/yahoo_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/yahoo_trans.gif\" alt=\"Add to: Yahoo\" name=\"Yahoo\" border=\"0\" id=\"Yahoo\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.spurl.net/\" onClick=\"window.open(\'http://www.spurl.net/spurl.php?v=3&amp;tags=&amp;title=\'+encodeURIComponent(document.title)+\'&amp;url=\'+encodeURIComponent(document.location.href));return false;\" title=\"Add to: Spurl\" onMouseOver=\"schnapp(\'Spurl\',\'\',\'http://asp.net.tr/img/spurl_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/spurl_trans.gif\" alt=\"Add to: Spurl\" name=\"Spurl\" border=\"0\" id=\"Spurl\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.google.com/\" onClick=\"window.open(\'http://www.google.com/bookmarks/mark?op=add&amp;hl=tr&amp;bkmk=\'+encodeURIComponent(location.href)+\'&amp;annotation=&amp;labels=&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Google\" onMouseOver=\"schnapp(\'Google\',\'\',\'http://asp.net.tr/img/google_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/google_trans.gif\" alt=\"Add to: Google\" name=\"Google\" border=\"0\" id=\"Google\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.blinklist.com/\" onClick=\"window.open(\'http://www.blinklist.com/index.php?Action=Blink/addblink.php&amp;Description=&amp;Tag=&amp;Url=\'+encodeURIComponent(location.href)+\'&amp;Title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Blinklist\" onMouseOver=\"schnapp(\'Blinklist\',\'\',\'http://asp.net.tr/img/blinklist_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/blinklist_trans.gif\" alt=\"Add to: Blinklist\" name=\"Blinklist\" border=\"0\" id=\"Blinklist\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://blogmarks.net/\" onClick=\"window.open(\'http://blogmarks.net/my/new.php?mini=1&amp;simple=1&amp;url=\'+encodeURIComponent(location.href)+\'&amp;content=&amp;public-tags=&amp;title=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Blogmarks\" onMouseOver=\"schnapp(\'Blogmarks\',\'\',\'http://asp.net.tr/img/blogmarks_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/blogmarks_trans.gif\" alt=\"Add to: Blogmarks\" name=\"Blogmarks\" border=\"0\" id=\"Blogmarks\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.diigo.com/\" onClick=\"window.open(\'http://www.diigo.com/post?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title)+\'&amp;tag=&amp;comments=\'); return false;\" title=\"Add to: Diigo\" onMouseOver=\"schnapp(\'Diigo\',\'\',\'http://asp.net.tr/img/diigo_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/diigo_trans.gif\" alt=\"Add to: Diigo\" name=\"Diigo\" border=\"0\" id=\"Diigo\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.technorati.com/\" onClick=\"window.open(\'http://technorati.com/faves?add=\'+encodeURIComponent(location.href)+\'&amp;tag=\');return false;\" title=\"Add to: Technorati\" onMouseOver=\"schnapp(\'Technorati\',\'\',\'http://asp.net.tr/img/technorati_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/technorati_trans.gif\" alt=\"Add to: Technorati\" name=\"Technorati\" border=\"0\" id=\"Technorati\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.newsvine.com/\" onClick=\"window.open(\'http://www.newsvine.com/_wine/save?popoff=1&amp;u=\'+encodeURIComponent(location.href)+\'&amp;tags=&amp;blurb=\'+encodeURIComponent(document.title));return false;\" title=\"Add to: Newsvine\" onMouseOver=\"schnapp(\'Newsvine\',\'\',\'http://asp.net.tr/img/newsvine_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/newsvine_trans.gif\" alt=\"Add to: Newsvine\" name=\"Newsvine\" border=\"0\" id=\"Newsvine\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.blinkbits.com/\" onClick=\"window.open(\'http://www.blinkbits.com/bookmarklets/save.php?v=1&amp;title=\'+encodeURIComponent(document.title)+\'&amp;source_url=\'+encodeURIComponent(location.href)+\'&amp;source_image_url=&amp;rss_feed_url=&amp;rss_feed_url=&amp;rss2member=&amp;body=\');return false;\" title=\"Add to: Blinkbits\" onMouseOver=\"schnapp(\'Blinkbits\',\'\',\'http://asp.net.tr/img/blinkbits_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/blinkbits_trans.gif\" alt=\"Add to: Blinkbits\" name=\"Blinkbits\" border=\"0\" id=\"Blinkbits\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://ma.gnolia.com/\" onClick=\"window.open(\'http://ma.gnolia.com/bookmarklet/add?url=\'+encodeURIComponent(location.href)+\'&amp;title=\'+encodeURIComponent(document.title)+\'&amp;description=&amp;tags=\');return false;\" title=\"Add to: Ma.Gnolia\" onMouseOver=\"schnapp(\'MaGnolia\',\'\',\'http://asp.net.tr/img/ma.gnolia_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/ma.gnolia_trans.gif\" alt=\"Add to: Ma.Gnolia\" name=\"MaGnolia\" border=\"0\" id=\"MaGnolia\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://smarking.com/\" onClick=\"window.open(\'http://smarking.com/editbookmark/?url=\'+ location.href +\'&amp;description=&amp;tags=\');return false;\" title=\"Add to: Smarking\" onMouseOver=\"schnapp(\'Smarking\',\'\',\'http://asp.net.tr/img/smarking_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/smarking_trans.gif\" alt=\"Add to: Smarking\" name=\"Smarking\" border=\"0\" id=\"Smarking\"> </a>");
document.writeln("<a rel=\"nofollow\" style=\"text-decoration:none;\" href=\"http://www.netvouz.com/\" onClick=\"window.open(\'http://www.netvouz.com/action/submitBookmark?url=\'+encodeURIComponent(location.href)+\'&amp;description=&amp;tags=&amp;title=\'+encodeURIComponent(document.title)+\'&amp;popup=yes\');return false;\" title=\"Add to: Netvouz\" onMouseOver=\"schnapp(\'Netvouz\',\'\',\'http://asp.net.tr/img/netvouz_trans_ani.gif\',1)\" onMouseOut=\"schnipp()\" > <img style=\"padding-bottom:1px;\" src=\"http://asp.net.tr/img/netvouz_trans.gif\" alt=\"Add to: Netvouz\" name=\"Netvouz\" border=\"0\" id=\"Netvouz\"> </a>");